Repository microsoft/DirectXTK, pull requests merged in 2024-02, with the labels that each got.

#426 Update GDK projects and ADO pipelines
  DirectXTK_GDK_2019.vcxproj
  DirectXTK_GDK_2022.vcxproj
  build/DirectXTK-GitHub-WSL-11.yml
  build/DirectXTK-GitHub-WSL.yml
  build/DirectXTK-OneFuzz.yml
Labels: maintainence

#428 fix warning for MSVC pragma syntax
  Audio/AudioEngine.cpp
  Audio/DynamicSoundEffectInstance.cpp
  Audio/SoundStreamInstance.cpp
  Audio/WaveBankReader.cpp
  Inc/Audio.h
  Inc/DirectXHelpers.h
  Inc/GamePad.h
  Inc/Keyboard.h
  Inc/Mouse.h
  Inc/ScreenGrab.h
  Inc/WICTextureLoader.h
  Src/GamePad.cpp
  Src/GraphicsMemory.cpp
  Src/Keyboard.cpp
  Src/Mouse.cpp
  Src/PlatformHelpers.h
  Src/pch.h
  XWBTool/xwbtool.cpp
Labels: conformance

#429 Update CMake to work with Intel compilers
  CMakeLists.txt
  CMakePresets.json
  Inc/GamePad.h
  Inc/Keyboard.h
  Inc/Mouse.h
  Src/WICTextureLoader.cpp
Labels: conformance

#431 CMake refactor
  CMakeLists.txt
  DirectXTK_Desktop_2019.vcxproj
  DirectXTK_Desktop_2019_Win10.vcxproj
  DirectXTK_Desktop_2022.vcxproj
  DirectXTK_Desktop_2022_Win10.vcxproj
  DirectXTK_GDK_2019.vcxproj
  DirectXTK_GDK_2022.vcxproj
  DirectXTK_Windows10_2019.vcxproj
  DirectXTK_Windows10_2022.vcxproj
  Src/pch.h
  build/CompilerAndLinker.cmake
Labels: maintainence

#432 Have CMake generate pkg-config file for library.
  CMakeLists.txt
  build/DirectXTK-GitHub-CMake-Dev17.yml
  build/DirectXTK-GitHub-CMake.yml
  build/DirectXTK.pc.in
  build/JoinPaths.cmake
Labels: maintainence

#434 Hotfix for CMake switch order
  build/CompilerAndLinker.cmake
Labels: bug
